GROUP_NAME_MAPPING = {
    "Application Commands": "app", "Project Commands": "project", "Element Commands": "elements",
    "Favorites Commands": "favorites", "Property Commands": "properties", "Attribute Commands": "attributes",
    "Library Commands": "library", "Navigator Commands": "navigator", "Issue Management Commands": "issues",
    "Revision Management Commands": "revisions", "Teamwork Commands": "teamwork", "Developer Commands": "dev",
}

MODULE_NAME_MAPPING = {
    short_name: full_name.replace(" ", "_").lower()
    for full_name, short_name in GROUP_NAME_MAPPING.items()
}

# All available groups for CLI argument choices
AVAILABLE_GROUPS = sorted(list(MODULE_NAME_MAPPING.keys()) + ['discovery'])


# --- Tool Generation Constants ---
COMMAND_DETAILS_URL = "https://raw.githubusercontent.com/SzamosiMate/multiconn_archicad/main/code_generation/schema/_command_details.json"
COMMAND_MODEL_NAMES_URL = "https://raw.githubusercontent.com/SzamosiMate/multiconn_archicad/main/code_generation/schema/_command_model_names.json"

COMMANDS_TO_EXCLUDE = {
    "GetProjectInfo", "GetArchicadLocation", "QuitArchicad", "GenerateDocumentation",
    "GetRevisionIssues", "SetPropertyValuesOfAttributes", "CreateZones",
}

PAGINATED_COMMANDS = {
    "GetAllElements": "elements",
    "GetSelectedElements": "elements",
    "GetElementsByType": "elements",
    "GetAllProperties": "properties",
    "GetAttributesByType": "attributes",
    "GetIssues": "issues"
}

GENERATION_FILE_HEADER = "# This file is auto-generated by generate_tools.py. DO NOT EDIT."
PAGINATED_DOCSTRING_ADDENDUM = """
    This response is paginated. If 'next_page_token' is returned, call this function
    again with that token to get the next page of results."""


# --- Pagination Constants ---
PAGINATION_CACHE_LIFETIME_SECONDS = 300
DEFAULT_PAGE_SIZE = 500


# --- Application/Server Constants ---
TAPIR_MCP_GROUP_ENV_VAR = 'TAPIR_MCP_GROUP'
DEFAULT_GROUP_NAME = 'Default'

SERVER_NAME_TEMPLATE = "Tapir_{group_name}"
SERVER_TITLE_TEMPLATE = "Archicad Tapir ({group_name})"
SERVER_DESCRIPTION_TEMPLATE = "A server to control Archicad. This server exposes the '{group_name}' toolset."