import json
import logging
import re
import urllib.request
from pathlib import Path
from textwrap import dedent, indent
from typing import Set

from generator_config import TAPIR_CONFIG, OFFICIAL_CONFIG, ApiSourceConfig

log = logging.getLogger()

REGISTER_AS_MCP_TOOLS = False

FILE_HEADER = "# This file is auto-generated by generate_tools.py. DO NOT EDIT."
PAGINATED_DOCSTRING_ADDENDUM = """
    This response is paginated. If 'next_page_token' is returned, call archicad_call_tool
    again with the same arguments and page_token set to that token to get the next page
    of results."""

def camel_to_snake(name: str) -> str:
    s1 = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def get_command_model_names(command_name: str) -> tuple[str, str]:
    return f"{command_name}Parameters", f"{command_name}Result"


def fetch_json_data(url: str, description: str) -> list | dict:
    log.info(f"Fetching {description} from {url}...")
    try:
        with urllib.request.urlopen(url) as response:
            if response.status == 200:
                log.info(f"Successfully fetched {description}.")
                return json.loads(response.read().decode("utf-8"))
            raise ConnectionError(f"Failed to fetch file: HTTP {response.status}")
    except urllib.request.HTTPError as e:
        log.error(f"Failed to fetch {description}: {e}")
        return []


def group_commands_by_category(command_details: list[dict]) -> dict[str, list[dict]]:
    grouped = {}
    for cmd in command_details:
        group_key = cmd["group"]
        grouped.setdefault(group_key, []).append(cmd)
    log.info(f"Grouped {len(command_details)} commands into {len(grouped)} categories.")
    return grouped


def prepare_output_directory(path: Path):
    if path.exists():
        log.warning(f"Output directory {path} exists. Cleaning...")
        for f in path.glob("*.py"):
            f.unlink()
    else:
        path.mkdir(parents=True, exist_ok=True)
    log.info(f"Prepared generation directory: {path}")


def _generate_imports_for_group(commands: list[dict], valid_model_names: set[str], config: ApiSourceConfig) -> str:
    imports = set()
    for cmd in commands:
        p_model, _ = get_command_model_names(cmd["name_camel"])
        if p_model in valid_model_names:
            imports.add(p_model)

    if not imports:
        return ""

    import_statements = ",\n".join(f"    {imp}" for imp in sorted(imports))
    return f"from multiconn_archicad.models.{config.name}.commands import (\n{import_statements},\n)"


def _generate_call_block(cmd: dict, has_params: bool, config: ApiSourceConfig) -> str:
    params_for_api_call = "params.model_dump(mode='json', by_alias=True, exclude_none=True)" if has_params else "{}"
    api_call = f'conn_header.core.{config.api_call_method}'
    return dedent(f'''
        return {api_call}(
            command="{cmd["name_for_api"]}",
            parameters={params_for_api_call}
        )
    ''')


def _generate_tool_function_code(command: dict, valid_model_names: set[str], config: ApiSourceConfig) -> str:
    command_name_camel = command["name_camel"]
    command_name_snake = camel_to_snake(command_name_camel)
    short_group_name = config.group_mapping.get(command["group"], "dev")
    tool_name = f"{short_group_name}_{command_name_snake}"

    params_model, _ = get_command_model_names(command_name_camel)
    has_params = params_model in valid_model_names
    is_paginated = command_name_camel in config.paginated_commands

    param_signature = f", params: {params_model}" if has_params else ""
    docstring_addendum = ""
    if is_paginated:
        docstring_addendum = PAGINATED_DOCSTRING_ADDENDUM
    return_annotation = "dict"
    call_block = _generate_call_block(command, has_params, config)
    param_reg_arg = params_model if has_params else "None"

    docstring = f'"""\n{indent(command["description"], "    ")}{indent(docstring_addendum, "    ")}\n    """'
    decorator = ""
    if REGISTER_AS_MCP_TOOLS:
        decorator = dedent(f'''
        @mcp.tool(
            name="{tool_name}",
            title="{command_name_camel}",
            description="{command["description"]}"
        )
        ''')

    pagination_registration_arg = ""
    if is_paginated:
        pagination_registration_arg = (
            f',\n        pagination_field="{config.paginated_commands[command_name_camel]}"'
        )

    function_code = f'''{decorator}def {command_name_snake}(conn_header: ConnHeader{param_signature}) -> {return_annotation}:
    {docstring}
{indent(call_block, "    ")}
'''
    registration_call = dedent(f"""
    register_tool_for_dispatch(
        {command_name_snake},
        name="{tool_name}",
        title="{command_name_camel}",
        description="{command["description"]}",
        params_model={param_reg_arg}{pagination_registration_arg}
    )
    """)
    return f"{function_code}\n{registration_call}".strip() + "\n"


def generate_tool_files(grouped_commands: dict[str, list[dict]], config: ApiSourceConfig, valid_model_names: set[str]):
    for group_name, commands in grouped_commands.items():
        file_name_base = group_name.replace(" ", "_").lower()
        file_path = config.output_dir / f"{file_name_base}.py"

        imports_block = _generate_imports_for_group(commands, valid_model_names, config)

        common_imports = [
            FILE_HEADER,
            "from multiconn_archicad.conn_header import ConnHeader",
            "from tapir_archicad_mcp.tools.tool_registry import register_tool_for_dispatch",
        ]
        if REGISTER_AS_MCP_TOOLS:
            common_imports.append("from tapir_archicad_mcp.app import mcp")
        if imports_block:
            common_imports.append(imports_block)

        file_content = ["\n".join(common_imports)]
        for cmd in sorted(commands, key=lambda x: x["name_camel"]):
            file_content.append(_generate_tool_function_code(cmd, valid_model_names, config))

        with open(file_path, "w", encoding="utf-8") as f:
            f.write("\n\n".join(file_content))
        log.info(f"Generated tool file: {file_path}")

def generate_init_file(config: ApiSourceConfig, module_names: set[str]):
    init_path = config.output_dir / "__init__.py"
    content = [FILE_HEADER, ""]
    for module_name in sorted(list(module_names)):
        content.append(f"from tapir_archicad_mcp.tools.generated.{config.name}.{module_name} import *")
    with open(init_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    log.info(f"Generated __init__.py file at {init_path}")


def run_generation_for_source(config: ApiSourceConfig) -> Set[str]:
    log.info(f"--- Starting Generation for {config.name.upper()} ---")

    # 1. Fetch organized commands JSON and valid model names
    all_organized_data = fetch_json_data(config.details_url, "Organized Commands")
    valid_model_names_list = fetch_json_data(config.model_names_url, f"{config.name} valid model names")

    if not all_organized_data or not valid_model_names_list:
        log.critical(f"Could not fetch data for {config.name}. Aborting this source.")
        return set()

    # 2. Extract and flatten commands for the current source ("tapir" or "official")
    source_groups: dict[str, list[dict]] = all_organized_data.get(config.name, {})

    grouped_commands: dict[str, list[dict]] = {}
    processed_count = 0

    for group_name, cmd_list in source_groups.items():
        for cmd in cmd_list:
            name_for_api = cmd["name"]
            name_camel = name_for_api.removeprefix(config.prefix_to_strip)

            if name_camel in config.commands_to_exclude:
                continue

            cmd_copy = dict(cmd)
            cmd_copy["name_camel"] = name_camel
            cmd_copy["name_for_api"] = name_for_api

            grouped_commands.setdefault(group_name, []).append(cmd_copy)
            processed_count += 1

    log.info(
        f"Generating tools for {processed_count} commands across {len(grouped_commands)} files from {config.name}.")

    valid_model_names = set(valid_model_names_list)

    # 3. Generate individual files and __init__.py
    prepare_output_directory(config.output_dir)
    generate_tool_files(grouped_commands, config, valid_model_names)

    generated_modules = {group_name.replace(" ", "_").lower() for group_name in grouped_commands.keys()}
    generate_init_file(config, generated_modules)

    log.info(f"--- Finished Generation for {config.name.upper()} ---")
    return {cmd["name_camel"] for cmds in grouped_commands.values() for cmd in cmds}


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
    log.info("--- Starting Archicad MCP Tool Generator ---")

    run_generation_for_source(TAPIR_CONFIG)
    run_generation_for_source(OFFICIAL_CONFIG)

    log.info("--- Tool Generation Completed Successfully for All Sources ---")
